apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-db
  labels:
    app: ecommerce-db
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: ecommerce-db
  template:
    metadata:
      labels:
        app: ecommerce-db
    spec:
      containers:
        - name: ecommerce-db
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flask-ecommerce-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: flask-ecommerce-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: flask-ecommerce-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flask-ecommerce-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}  
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-db-service
spec:
  selector:
    app: ecommerce-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
